# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FormPro' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FormPro

  

  platform :ios, '9.0'

  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNSketchCanvas', :path => '../node_modules/@terrylinla/react-native-sketch-canvas'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNShare', :path => '../node_modules/react-native-share'



  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'FormProTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FormPro-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FormPro-tvOS

  target 'FormPro-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end